#!/usr/bin/env python3
"""
Preprocess the Tzeva Adom historical dataset into compact files for the generator.

Inputs  : data/raw.json   (raw event array from tzevaadom.co.il/static/historical/all.json)
Outputs : data/data.js    (compact, embeddable: window.ALERTS_DATA = {...})
          data/daily.json  (per-day aggregate by threat type)

Run:  python3 preprocess.py
Refresh data first with:
  curl -s https://www.tzevaadom.co.il/static/historical/all.json -o data/raw.json
"""
import json
import os
from collections import defaultdict, Counter
from datetime import datetime, timezone

try:
    from zoneinfo import ZoneInfo
    IL = ZoneInfo("Asia/Jerusalem")
except Exception:
    IL = None

HERE = os.path.dirname(os.path.abspath(__file__))
RAW = os.path.join(HERE, "data", "raw.json")

THREAT_TYPES = {
    0: "Rocket / Missile",
    2: "Hostile Aircraft",
    3: "Earthquake",
    5: "Hostile UAV / Drone",
    8: "Radiological / CBRN",
}


def il_date(ts):
    """Return YYYY-MM-DD in Israel local time."""
    if IL:
        return datetime.fromtimestamp(ts, IL).strftime("%Y-%m-%d")
    return datetime.fromtimestamp(ts, timezone.utc).strftime("%Y-%m-%d")


def main():
    with open(RAW, encoding="utf-8") as f:
        data = json.load(f)

    # Build a city dictionary so events reference cities by integer index.
    city_index = {}
    cities = []

    def cidx(name):
        if name not in city_index:
            city_index[name] = len(cities)
            cities.append(name)
        return city_index[name]

    # Compact events: [threatId, ts, [cityIdx, ...]]
    events = []
    city_counts = Counter()       # city -> number of alert events touching it
    type_counts = Counter()       # threatId -> events
    daily = defaultdict(lambda: defaultdict(int))  # date -> threatId -> count

    timestamps = []
    for alert_id, threat_id, city_list, ts in data:
        idxs = [cidx(c) for c in city_list]
        events.append([threat_id, ts, idxs])
        timestamps.append(ts)
        type_counts[threat_id] += 1
        daily[il_date(ts)][threat_id] += 1
        for c in city_list:
            city_counts[c] += 1

    # Sort events chronologically (raw data is not strictly ordered).
    events.sort(key=lambda e: e[1])

    tmin, tmax = min(timestamps), max(timestamps)

    # Per-city totals, sorted most-hit first.
    city_totals = sorted(
        ({"i": city_index[c], "n": c, "c": n} for c, n in city_counts.items()),
        key=lambda x: -x["c"],
    )

    # Daily aggregate, sorted by date.
    daily_rows = []
    for date in sorted(daily.keys()):
        row = {"d": date, "t": dict(daily[date])}
        row["sum"] = sum(daily[date].values())
        daily_rows.append(row)

    meta = {
        "generated": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "events": len(events),
        "cityRows": sum(city_counts.values()),
        "cities": len(cities),
        "tmin": tmin,
        "tmax": tmax,
        "threatTypes": THREAT_TYPES,
        "typeCounts": dict(type_counts),
        "source": "https://www.tzevaadom.co.il/static/historical/all.json",
    }

    payload = {
        "meta": meta,
        "cities": cities,
        "cityTotals": city_totals,
        "events": events,
    }

    # data.js — embeddable so the app works from file:// with no server.
    out_js = os.path.join(HERE, "data", "data.js")
    with open(out_js, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by preprocess.py — do not edit by hand.\n")
        f.write("window.ALERTS_DATA = ")
        json.dump(payload, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")

    out_daily = os.path.join(HERE, "data", "daily.json")
    with open(out_daily, "w", encoding="utf-8") as f:
        json.dump(daily_rows, f, ensure_ascii=False, separators=(",", ":"))

    print(f"events     : {len(events)}")
    print(f"city-rows  : {sum(city_counts.values())}")
    print(f"cities     : {len(cities)}")
    print(f"date range : {il_date(tmin)} -> {il_date(tmax)}")
    print(f"by type    : {{ {', '.join(f'{THREAT_TYPES.get(k,k)}: {v}' for k,v in type_counts.most_common())} }}")
    print(f"wrote      : {out_js} ({os.path.getsize(out_js)/1024/1024:.2f} MB)")
    print(f"wrote      : {out_daily} ({os.path.getsize(out_daily)/1024:.0f} KB)")


if __name__ == "__main__":
    main()
